# Generated by Django 4.0.5 on 2022-08-15 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='cuerpo',
            field=models.TextField(max_length=240),
        ),
    ]
