# Generated by Django 4.0.5 on 2022-08-15 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_cuerpo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='fecha',
        ),
    ]
