# Generated by Django 4.0.5 on 2022-08-15 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_blog_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='imagen',
        ),
    ]
